# Local development overrides

url: "http://localhost:4000"
baseurl: ""
environment: development

# Disable or stub things for local testing
google_analytics: ""  # Prevent tracking locally

# Enable viewing of draft posts
show_drafts: true

# Optional override if needed (in case you want to swap styles locally)
site:
  css: style.css

sass:
  style: expanded
  load_paths:
    - _sass
  quiet_deps: true
